apiVersion: v1
kind: Service
metadata:
  name: control-plane-api
spec:
  selector:
    app: control-plane-api
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30080
  type: NodePort
