apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kocao-system

resources:
  - namespace.yaml
  - crd-session.yaml
  - crd-harnessrun.yaml
  - serviceaccount.yaml
  - api-rbac.yaml
  - operator-rbac.yaml
  - api-deployment.yaml
  - api-service.yaml
  - operator-deployment.yaml

configMapGenerator:
  - name: control-plane-caddy-config
    files:
      - caddy/Caddyfile
  - name: control-plane-caddy-static
    files:
      - caddy/index.html
      - caddy/scalar.html

generatorOptions:
  disableNameSuffixHash: true
